# Generated by Django 3.0.1 on 2019-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventoryreq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('bought_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
