# Generated by Django 3.0.1 on 2019-12-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreq',
            name='expire_date',
            field=models.DateField(blank=True),
        ),
    ]
