# Generated by Django 3.0.1 on 2019-12-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191231_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreq',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
