# Generated by Django 3.0.1 on 2019-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191231_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreq',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
