# Generated by Django 3.0.1 on 2019-12-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20191231_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreq',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
