# Generated by Django 3.0.1 on 2019-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phoneno', models.IntegerField(max_length=10)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('cash', models.BooleanField(blank=True, default=True)),
                ('card', models.BooleanField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100000)),
            ],
        ),
    ]
