# Generated by Django 3.0.1 on 2020-01-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_recordmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='amount',
        ),
    ]
