# Generated by Django 3.0.1 on 2020-01-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_paymentdetails_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordmodel',
            name='items_ids',
        ),
        migrations.RemoveField(
            model_name='recordmodel',
            name='items_quantity',
        ),
        migrations.RemoveField(
            model_name='recordmodel',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='recordmodel',
            name='payment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.paymentdetails'),
            preserve_default=False,
        ),
    ]
