# Generated by Django 3.0.1 on 2020-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20200129_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
