# Generated by Django 3.0.2 on 2020-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20200130_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='recordmodel',
        ),
    ]
