# Generated by Django 3.0.2 on 2020-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20200130_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000),
        ),
    ]
